import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/manual/Navbar/Navbar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Garv's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` m-auto max-w-7xl w-full ${poppins.variable} bg-black  antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
